const fs=require('fs'),os=require('os'),path=require('path');
const {SCHEMA_VERSION,openStore,migrate}=require('../storage');
const {initializeDatabase}=require('../init-db');
const {backupAndMigrate}=require('../migrate');
test('backup-first 16 to current schema upgrade preserves account records and prior snapshot',async()=>{
  const directory=fs.mkdtempSync(path.join(os.tmpdir(),'easy-fetch-upgrade-'));
  const filename=path.join(directory,'legacy.db');
  let db;
  try {
    initializeDatabase(filename);db=openStore(filename);
    // Reconstruct v16 by removing additive later tables and version entries.
    db.exec(`DROP TRIGGER publication_delivery_receipt_binding;
      DROP TRIGGER publication_delivery_receipt_no_update;
      DROP TRIGGER publication_delivery_receipt_no_delete;
      DROP TRIGGER publication_delivery_done_receipt;
      DROP TRIGGER publication_delivery_no_done_insert;
      DROP TRIGGER publication_delivery_terminal;
      DROP TABLE publication_delivery_receipts; DROP TABLE publication_sinks`);
    db.exec(`DROP TRIGGER claim_restriction_owner; DROP TRIGGER source_restriction_owner;
      DROP TABLE publication_invalidation_receipts; DROP TABLE publication_delivery_tasks;
      DROP TABLE publication_outbox; DROP TABLE publication_manifest_heads;
      DROP TABLE publication_dependencies; DROP TABLE publication_events;
      DROP TABLE publication_snapshots; DROP TABLE publication_review_events;
      DROP TABLE publication_owner_events`);
    db.exec(`DROP TRIGGER work_admission_state_audited; DROP TRIGGER work_admission_state_no_delete;
      DROP TRIGGER work_admission_events_no_update; DROP TRIGGER work_admission_events_no_delete;
      DROP TABLE work_admission_events; DROP TABLE work_admission_state;
      DROP INDEX claim_jobs_active_leases; DROP INDEX claim_jobs_backlog;
      DROP INDEX fetch_jobs_active_leases; DROP INDEX rebuild_jobs_active_leases;
      ALTER TABLE claim_jobs DROP COLUMN pause_blocked_version;
      ALTER TABLE claim_jobs DROP COLUMN pause_blocked_at_ms;
      ALTER TABLE claim_jobs DROP COLUMN retry_ready_at_ms;
      ALTER TABLE claim_jobs DROP COLUMN eligible_at_ms;
      ALTER TABLE claim_jobs DROP COLUMN created_at_ms;
      ALTER TABLE claim_jobs DROP COLUMN pause_credit_version;
      ALTER TABLE claim_jobs DROP COLUMN dispatch_started_at_ms;
      DROP TRIGGER claim_jobs_identity_immutable;
      DROP TRIGGER claim_job_review_no_update; DROP TRIGGER claim_job_review_no_delete;
      DROP TRIGGER provider_queue_recovery_no_update; DROP TRIGGER provider_queue_recovery_no_delete;
      DROP TABLE claim_job_review_events; DROP TABLE provider_queue_recovery_events;
      DROP INDEX claim_jobs_provider_recovery;
      DROP INDEX claim_job_identity;
      ALTER TABLE claim_jobs DROP COLUMN stage;
      CREATE UNIQUE INDEX claim_job_identity ON claim_jobs(claim_id,COALESCE(context_version_id,0),passage_id,model,question_version,policy_version);
      ALTER TABLE provider_queue_state DROP COLUMN pause_version;
      DROP TRIGGER model_call_failure_metadata_no_update; DROP TRIGGER model_call_failure_metadata_no_delete;
      DROP TABLE model_call_failure_metadata; DROP TABLE provider_queue_state;
      ALTER TABLE claim_jobs DROP COLUMN task_deadline_at;
      DROP TRIGGER model_reservations_budget_projection;
      DROP TRIGGER model_settlements_budget_projection; DROP TRIGGER model_settlements_unknown_projection;
      DROP TRIGGER model_late_holds_projection; DROP TRIGGER model_late_hold_resolution_projection;
      DROP TRIGGER model_settlements_final_once; DROP INDEX model_reservations_period_category;
      DROP TABLE model_budget_guard_restorations; DROP TABLE model_budget_guard_rearms;
      DROP TABLE model_late_hold_resolutions; DROP TABLE model_late_charge_holds;
      DROP TABLE model_budget_integrity_fault_events; DROP TABLE model_call_legacy_recovery;
      DROP TABLE model_call_legacy_recovery_seal;
      DROP TABLE model_call_late_events; DROP TABLE model_call_recovery_events;
      DROP TABLE model_charge_reconciliations; DROP TABLE model_budget_alert_events;
      DROP TABLE model_call_usage_events; DROP TABLE model_call_slot_events;
      DROP TABLE model_reservation_admissions; DROP TABLE model_budget_policy_events;
      DROP TABLE model_budget_pending; DROP TABLE model_budget_counters; DROP TABLE model_budget_clock`);
    db.exec('DROP TABLE analysis_verification_permission_events; DROP TABLE analysis_verification_jobs; DROP TABLE analysis_verification_reports; DROP TABLE analysis_versions; DROP TABLE claim_retrieval_results; DROP TABLE claim_retrieval_variants; DROP TABLE claim_retrieval_runs; DROP TRIGGER research_passages_normalize; DROP TABLE passage_normalized_search; DROP TABLE passage_normalizations; DROP TABLE claim_relationship_revocations; DROP TABLE claim_relationships; DROP TABLE claim_search_attempts; DROP TABLE claim_coverage_events; DROP TABLE source_chain_links; DROP TABLE extraction_renders');
    db.exec("DROP TABLE extraction_review_events; DROP TABLE extraction_manifests; DROP TABLE fetch_receipts; DROP TABLE fetch_jobs; DROP TABLE source_fetch_limits; DELETE FROM rebuild_migrations WHERE version>=17; INSERT INTO users(id,username,password) VALUES(1,'fixture','disabled'); INSERT INTO google_identities(subject,user_id) VALUES('fixture-subject',1); INSERT INTO user_roles(user_id,role) VALUES(1,'editor')");
    db.close();
    const backup=await backupAndMigrate(filename,directory);
    db=openStore(filename);
    expect(db.prepare('SELECT MAX(version) v FROM rebuild_migrations').get().v).toBe(SCHEMA_VERSION);
    expect(db.prepare('SELECT COUNT(*) n FROM extraction_review_events').get().n).toBe(0);
    expect(db.prepare('SELECT COUNT(*) n FROM extraction_manifests').get().n).toBe(0);
    expect(db.prepare('SELECT COUNT(*) n FROM fetch_receipts').get().n).toBe(0);
    expect(db.prepare('SELECT COUNT(*) n FROM fetch_jobs').get().n).toBe(0);
    expect(db.prepare('SELECT role FROM user_roles WHERE user_id=1').get().role).toBe('editor');
    expect(db.prepare('SELECT subject FROM google_identities WHERE user_id=1').get().subject).toBe('fixture-subject');
    db.exec("INSERT INTO source_fetch_limits VALUES('records.example.org',12345)");
    migrate(db);
    expect(db.prepare('SELECT next_allowed_ms FROM source_fetch_limits').get().next_allowed_ms).toBe(12345);
    const old=openStore(backup);
    try {
      expect(old.prepare('SELECT MAX(version) v FROM rebuild_migrations').get().v).toBe(16);
      expect(old.prepare("SELECT name FROM sqlite_master WHERE name='source_fetch_limits'").get()).toBeUndefined();
      expect(old.prepare('SELECT role FROM user_roles WHERE user_id=1').get().role).toBe('editor');
      expect(old.pragma('integrity_check',{simple:true})).toBe('ok');
    } finally {old.close();}
  } finally {if(db?.open)db.close();fs.rmSync(directory,{recursive:true,force:true});}
});
